import type { AcceptanceCheck } from '../gate.js';
import type { ProductionRunInput } from '../../shared/production-schema.js';

const escape = (text: string) => text.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]!));
/** Engineering fixture only; explicit case configuration, never keyword inference. */
export function demoHtml(input: ProductionRunInput) { return `<!doctype html><html lang="zh"><head><meta charset="utf-8"><title>离线任务清单</title><style>body{font:18px system-ui;max-width:700px;margin:40px auto;padding:24px;color:#17212c}input,button{font:inherit;padding:12px}li{margin:18px 0}#notice{background:#fff6da;padding:12px}.done{text-decoration:line-through}output{padding:8px}</style></head><body><h1>${escape(input.brief.slice(0, 180))}</h1><p id="notice">工程 Mock 夹具，不是真实模型自主交付。</p><label for="task-input">任务名称</label><input id="task-input" maxlength="120"><button id="add-task">添加</button><p id="feedback">请输入任务</p><button id="show-all">全部</button><button id="show-open">未完成</button><button id="show-done">已完成</button><ul id="tasks"></ul><p>任务数量 <output id="count">0</output> 完成数量 <output id="done-count">0</output></p><script>const tasks=[];let filter='all';let nextId=0;const input=document.querySelector('#task-input');const feedback=document.querySelector('#feedback');function render(){const list=document.querySelector('#tasks');list.replaceChildren();tasks.forEach(task=>{if(filter==='open'&&task.done||filter==='done'&&!task.done)return;const li=document.createElement('li');li.dataset.taskId=String(task.id);const span=document.createElement('span');span.textContent=task.title;span.className=task.done?'done':'';const button=document.createElement('button');button.className='toggle';button.textContent=task.done?'恢复':'完成';button.onclick=()=>{task.done=!task.done;render()};const remove=document.createElement('button');remove.className='delete';remove.textContent='删除';remove.onclick=()=>{tasks.splice(tasks.findIndex(item=>item.id===task.id),1);render()};li.append(span,button,remove);list.append(li)});document.querySelector('#count').textContent=String(tasks.length);document.querySelector('#done-count').textContent=String(tasks.filter(task=>task.done).length)}document.querySelector('#add-task').onclick=()=>{const title=input.value.trim();if(!title){feedback.textContent='任务不能为空';return}tasks.push({id:nextId++,title,done:false});input.value='';feedback.textContent='已添加';render()};document.querySelector('#show-all').onclick=()=>{filter='all';render()};document.querySelector('#show-open').onclick=()=>{filter='open';render()};document.querySelector('#show-done').onclick=()=>{filter='done';render()};render();</script></body></html>`; }
export function demoChecks(caseId: ProductionRunInput['demoCaseId']): AcceptanceCheck[] {
  const disclaimer: AcceptanceCheck = { name: 'Mock 边界可见与初始零任务', steps: [{ action: 'assertText', selector: '#notice', text: 'Mock' }, { action: 'assertTextExact', selector: '#count', text: '0' }, { action: 'assertCount', selector: '#tasks li', count: 0 }] };
  if (caseId === 'feature') return [disclaimer, { name: '两任务状态筛选与统计回归', steps: [{ action: 'fill', selector: '#task-input', value: '编写方案' }, { action: 'click', selector: '#add-task' }, { action: 'fill', selector: '#task-input', value: '执行测试' }, { action: 'click', selector: '#add-task' }, { action: 'click', selector: '[data-task-id="0"] .toggle' }, { action: 'assertTextExact', selector: '#done-count', text: '1' }, { action: 'click', selector: '#show-open' }, { action: 'assertTextExact', selector: '#tasks li span', text: '执行测试' }, { action: 'assertCount', selector: '#tasks li', count: 1 }, { action: 'click', selector: '#show-done' }, { action: 'assertTextExact', selector: '#tasks li span', text: '编写方案' }, { action: 'assertCount', selector: '#tasks li', count: 1 }, { action: 'click', selector: '#show-all' }, { action: 'assertCount', selector: '#tasks li', count: 2 }, { action: 'assertTextExact', selector: '#count', text: '2' }, { action: 'assertTextExact', selector: '#done-count', text: '1' }] }];
  if (caseId === 'bugfix') return [disclaimer, { name: '拒绝空输入及空格，连续添加和删除不丢项', steps: [{ action: 'click', selector: '#add-task' }, { action: 'assertCount', selector: '#tasks li', count: 0 }, { action: 'assertTextExact', selector: '#feedback', text: '任务不能为空' }, { action: 'fill', selector: '#task-input', value: '   ' }, { action: 'click', selector: '#add-task' }, { action: 'assertCount', selector: '#tasks li', count: 0 }, { action: 'assertTextExact', selector: '#feedback', text: '任务不能为空' }, { action: 'fill', selector: '#task-input', value: '回归接口' }, { action: 'click', selector: '#add-task' }, { action: 'fill', selector: '#task-input', value: '检查日志' }, { action: 'click', selector: '#add-task' }, { action: 'assertCount', selector: '#tasks li', count: 2 }, { action: 'assertTextExact', selector: '#count', text: '2' }, { action: 'click', selector: '[data-task-id="0"] .delete' }, { action: 'assertCount', selector: '#tasks li', count: 1 }, { action: 'assertTextExact', selector: '#count', text: '1' }, { action: 'assertTextExact', selector: '#tasks li span', text: '检查日志' }] }];
  return [disclaimer, { name: '新增、完成、删除与精确统计', steps: [{ action: 'fill', selector: '#task-input', value: '准备发布' }, { action: 'click', selector: '#add-task' }, { action: 'assertCount', selector: '#tasks li', count: 1 }, { action: 'assertTextExact', selector: '#tasks li span', text: '准备发布' }, { action: 'assertValue', selector: '#task-input', value: '' }, { action: 'assertTextExact', selector: '#count', text: '1' }, { action: 'click', selector: '.toggle' }, { action: 'assertTextExact', selector: '#done-count', text: '1' }, { action: 'click', selector: '.delete' }, { action: 'assertCount', selector: '#tasks li', count: 0 }, { action: 'assertTextExact', selector: '#count', text: '0' }, { action: 'assertTextExact', selector: '#done-count', text: '0' }] }];
}
