import { z } from 'zod';
import type { JevEvaluation, JevPublicConfig } from './jev-schema.js';
import type { CameraVerification } from './camera-scene-schema.js';

export const PRODUCTION_CAPABILITIES = ['offline-single-html', 'camera-scene-v1'] as const;
export type ProductionCapability = (typeof PRODUCTION_CAPABILITIES)[number];

export const PRODUCTION_ROLES = ['product', 'project-manager', 'researcher', 'developer', 'tester', 'verifier'] as const;
export type ProductionRole = (typeof PRODUCTION_ROLES)[number];
export const PRODUCTION_ROLE_LABELS: Record<ProductionRole, string> = { product: '产品经理', 'project-manager': '项目经理', researcher: '研究员', developer: '研发', tester: '测试', verifier: 'Verifier' };
export const PRODUCTION_CREDENTIAL_POLICY_VERSION = 'visible-token-v1';
const credentialMessage = 'API Key 必须为 16–500 个可见 ASCII 字符，不含空格、引号、反斜杠或控制字符；清除请使用 null';
const reservedCredentialValues = new Set(['fixture-with-real-jev', 'openai-compatible', 'user-declared-real', 'budgetAuthorized', 'selectedCandidateId', 'providerRequests', 'outputPerMillion', 'actualProviderRequests', 'harnessInvocations']);
export const productionApiKeySchema = z.string().min(16, credentialMessage).max(500, credentialMessage).refine(value => /^[\x21-\x7e]+$/.test(value) && !/["'\\]/.test(value), credentialMessage).refine(value => !reservedCredentialValues.has(value) && !/^(?:production-(?:html|acceptance|delivery|submission)-v\d+|raw-wire-usage-v\d+|verifier-ordinal-v\d+|jev-candidate-v\d+|visible-token-v\d+|mock-package-v\d+|city-agent-autonomous-production-public-v\d+)$/.test(value), 'API Key 不得与平台协议字段、状态或版本标识相同');
export const pricingSchema = z.object({ inputPerMillion: z.number().finite().nonnegative().max(10000), outputPerMillion: z.number().finite().nonnegative().max(10000), currency: z.enum(['USD', 'CNY']) }).strict();
const baseUrl = z.string().trim().url().max(500).refine(value => { const u = new URL(value); return ['http:', 'https:'].includes(u.protocol) && !u.username && !u.password && !u.search && !u.hash; }, 'Base URL 必须是无凭据/查询参数的 HTTP(S) 地址');
export const productionAgentInputSchema = z.object({ name: z.string().trim().min(1).max(80), role: z.enum(PRODUCTION_ROLES), provider: z.enum(['openai-compatible', 'anthropic', 'deepseek']).default('deepseek'), baseUrl: baseUrl.default('https://api.deepseek.com'), modelId: z.string().trim().min(1).max(150).default('deepseek-chat'), apiKey: productionApiKeySchema.nullable().optional(), enabled: z.boolean().default(true), pricing: pricingSchema.nullable().optional() }).strict();
export const productionAgentPatchSchema = productionAgentInputSchema.partial();
export type ProductionAgentInput = z.input<typeof productionAgentInputSchema>;
export interface ProductionAgent { id: string; name: string; role: ProductionRole; provider: 'openai-compatible' | 'anthropic' | 'deepseek'; baseUrl: string; modelId: string; hasApiKey: boolean; enabled: boolean; pricing?: z.infer<typeof pricingSchema>; }
export const productionLimitsSchema = z.object({ maxCalls: z.number().int().min(12).max(80).default(24), maxRepairCycles: z.number().int().min(0).max(2).default(2), maxTokens: z.number().int().min(2048).max(5_000_000).default(500000), maxOutputTokens: z.number().int().min(128).max(12000).default(6000), maxDurationMs: z.number().int().min(1000).max(1800000).default(600000), maxCost: z.number().finite().positive().max(10000).default(5), currency: z.enum(['USD', 'CNY']).default('USD') }).strict();
export const productionRunInputSchema = z.object({ brief: z.string().trim().min(3).max(6000), capability: z.enum(PRODUCTION_CAPABILITIES).default('offline-single-html'), mode: z.enum(['demo', 'mock-jev', 'live']).default('demo'), verifierEngine: z.enum(['llm-rubric', 'jev-cascade']).default('llm-rubric'), demoCaseId: z.enum(['create', 'feature', 'bugfix']).optional(), agentIds: z.array(z.string().uuid()).length(6), candidateCount: z.union([z.literal(1), z.literal(2)]).default(1), limits: productionLimitsSchema.default(() => productionLimitsSchema.parse({})), requirement: z.object({ id: z.string().trim().min(1).max(80), source: z.string().trim().min(1).max(300), background: z.string().max(3000).default(''), acceptance: z.string().trim().min(1).max(3000), difficulty: z.enum(['low', 'medium', 'high']).default('low'), kind: z.enum(['illustrative', 'user-declared-real']).default('illustrative') }).strict(), budgetAuthorized: z.boolean().default(false) }).strict().refine(input => input.mode !== 'live' || input.demoCaseId === undefined, '真实运行不接受演示题专用配置').refine(input => input.capability !== 'camera-scene-v1' || input.mode === 'live', '摄像头场景能力只支持明确授权的真实模式，不接受演示夹具回退');
export type ProductionRunInput = z.infer<typeof productionRunInputSchema>;
export type ProductionRunStatus = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled' | 'interrupted';
export interface ProductionProviderUsage { requests: number; deniedRequests: number; status: number | null; transportComplete: boolean; httpEof?: boolean; protocolComplete?: boolean; inputReported: boolean; outputReported: boolean; inputTokens: number | null; outputTokens: number | null; complete: boolean; }
export interface ProductionCall { id: string; role: ProductionRole; candidateId: string; phase: string; executionSource: 'mock' | 'injected' | 'harness'; providerRequests?: ProductionProviderUsage; startedAt: string; finishedAt?: string; model: Pick<ProductionAgent, 'id' | 'provider' | 'baseUrl' | 'modelId'>; promptVersion: string; promptHash: string; configHash: string; systemPrompt: string; userPrompt: string; rawOutput: string; error?: string; usage: { inputTokens: number | null; outputTokens: number | null; estimatedCost: number | null; currency: string }; selected?: boolean; }
export interface ProductionEvent { id: string; time: string; phase: string; role?: ProductionRole; message: string; }
export interface ProductionVerification { phase: string; engine?: 'llm-rubric' | 'jev' | 'jev-llm-fallback'; candidateIds: string[]; selectedCandidateId: string | null; criteriaHash: string; scores: Array<{ candidateId: string; score: number; reason: string }>; decision: 'accept' | 'abstain'; reason: string; }
export interface ProductionJevCall { id: string; phase: string; startedAt: string; configHash: string; evaluation: JevEvaluation; }
export interface ProductionGate { passed: boolean; checks: Array<{ name: string; passed: boolean; detail?: string }>; summary?: string; evidenceScope?: 'scene-behavior-synthetic'; }
export interface ProductionRun { id: string; input: ProductionRunInput; status: ProductionRunStatus; createdAt: string; finishedAt?: string; durationMs?: number; evidenceKind: 'fixture' | 'fixture-with-real-jev' | 'real-model' | 'injected-test'; platformCommit?: string; cameraVerification?: CameraVerification; jevSnapshot?: JevPublicConfig; jevCalls?: ProductionJevCall[]; agentSnapshot: ProductionAgent[]; events: ProductionEvent[]; calls: ProductionCall[]; verifications: ProductionVerification[]; outputs: Array<{ phase: string; role: ProductionRole; value: unknown; selectedCandidateId: string }>; frozenContract?: { version: string; hash: string; requirementHash: string; checks: unknown[]; frozenAt: string; capability?: ProductionCapability; runtimeVersion?: string; runtimeHash?: string; mandatoryChecksVersion?: string }; gateHistory: ProductionGate[]; gate?: ProductionGate; repairs: number; error?: string; usage: { inputTokens: number | null; outputTokens: number | null; estimatedCost: number | null; currency: string; complete: boolean }; interventions: Array<{ time: string; reason: string; type: 'cancel' }>; artifacts: Array<{ name: string; type: string }>; }
