import { z } from 'zod';
import type { JevEvaluation, JevPublicConfig } from './jev-schema.js';
import type { CameraVerification } from './camera-scene-schema.js';
import type { productionCoverageContract } from './production-coverage.js';
import type { ProductionExecutionIdentity } from '../server/production/provenance.js';
import type { JsonOutputDiagnostic } from '../server/production/output-diagnostics.js';
import type { VerifierDecisionDiagnostic } from '../server/production/verifier-diagnostics.js';
import type { AcceptanceCapacityDiagnostic } from '../server/production/acceptance-diagnostics.js';
import type { AcceptancePlan, AcceptanceGroup } from '../server/production/acceptance-plan.js';
import type { AcceptanceCheck } from '../server/gate.js';
import { IMPLEMENTATION_EVIDENCE_PROTOCOL_LITERALS, type ImplementationEvidence, type ImplementationEvidenceContract, type ImplementationEvidenceDiagnostic } from './production-implementation-evidence.js';

export interface ProductionValidationContract { acceptanceStrategy?: 'planned-groups-v1'; acceptanceConstructionVersion?: string; acceptancePlanVersion?: string; acceptanceGroupVersion?: string; implementationEvidencePolicy?: 'source-bound-v1'; implementationEvidenceVersion?: string; planningLoopVersion?: string; reviewContextVersion?: string; htmlExecutionProfileVersion?: string; outputDiagnosticsVersion?: string; acceptanceDiagnosticsVersion?: string; acceptancePlanningVersion?: string; verifierDiagnosticsVersion?: string; harnessPromptTransportVersion?: string; harnessJsonOutputVersion?: string; responseFormatPolicy?: 'deepseek-json-object-other-prompt-only'; semanticsVersion: string; jevRequestLayoutVersion?: string; cameraTestSemanticsVersion?: string; coverage: ReturnType<typeof productionCoverageContract>; }

export const PRODUCTION_CAPABILITIES = ['offline-single-html', 'camera-scene-v1'] as const;
export type ProductionCapability = (typeof PRODUCTION_CAPABILITIES)[number];

export const PRODUCTION_ROLES = ['product', 'project-manager', 'researcher', 'developer', 'tester', 'verifier'] as const;
export type ProductionRole = (typeof PRODUCTION_ROLES)[number];
export const PRODUCTION_ROLE_LABELS: Record<ProductionRole, string> = { product: '产品经理', 'project-manager': '项目经理', researcher: '研究员', developer: '研发', tester: '测试', verifier: 'Verifier' };
// Fresh defaults only; never rewrite persisted models or historical snapshots.
// Verified 2026-10-08: https://api-docs.deepseek.com/updates/ (2026-09-10 release; legacy IDs discontinued 2026-07-24).
export const PRODUCTION_DEFAULT_MODEL_ID = 'deepseek-flash' as const;
export const PRODUCTION_CREDENTIAL_POLICY_VERSION = 'visible-token-v2';
export const PRODUCTION_REPAIR_POLICY_VERSION = 'production-global-repair-v1';
export const PRODUCTION_PLANNING_LOOP_VERSION = 'production-planning-loop-v1';
const credentialMessage = 'API Key 必须为 16–500 个可见 ASCII 字符，不含空格、引号、反斜杠或控制字符；清除请使用 null';
// Redaction is literal replacement: a valid credential must not be a substring
// of these new transport protocol identifiers, not merely differ from them.
const protectedJsonOutputLiterals = ['harnessJsonOutputVersion', 'harness-json-output-v1', 'responseFormatPolicy', 'deepseek-json-object-other-prompt-only', 'production-review-context-v2', 'generationCodeReference', 'role-call.userPrompt.context.feedback.previousHtml', 'priorCandidateId', 'production-html-execution-v1', 'htmlExecutionProfileVersion', 'nativeFormSubmission', 'independentPagePerCheck', 'inlineScriptsAndStyles', 'localInputHandling', 'gateInteractions', 'disabled-before-submit-event', 'allowed-without-eval-or-external-resources', 'explicit-button-click', 'local-key-handler', 'production-boot-disk-v1', 'executionIdentity', 'sourceFingerprint', 'buildFingerprint', 'execution-identity-unready', 'execution-identity-drift'] as const;
const reservedCredentialValues = new Set(['fullPinsLocation', 'jev-request-layout-v2', 'requestLayoutVersion', 'jevRequestLayoutVersion', 'testSemanticsVersion', 'platformMandatoryGate', 'platformEngineering', 'physicalAcceptance', 'invariantUnderCssInteraction', 'cameraBusinessConstraints', 'cameraConstraintSchema', 'hostOverallReasonMaximum', 'validationContract', 'validationContractHash', 'semanticsVersion', 'cameraTestSemanticsVersion', 'acceptanceSemanticsVersion', 'coverageContract', 'compactOutputPolicy', 'hostCandidateReasonMaximum', 'hostOverallReasonMaximum', 'candidateReasonTargetCharacters', 'overallReasonTargetCharacters', 'fixture-with-real-jev', 'openai-compatible', 'user-declared-real', 'budgetAuthorized', 'selectedCandidateId', 'providerRequests', 'outputPerMillion', 'actualProviderRequests', 'harnessInvocations', 'stage-regeneration', 'repairPolicyVersion', 'rejectedCandidateIds', 'remainingRepairs', 'rawOutputExcerpt', 'rawOutputTruncated', 'rawOutputSha256', 'arithmetic-drift', 'jev-llm-protocol-fallback', 'score-mean-drift', 'score-concentration-drift', 'choice-concentration-drift', 'production-output-contract-v1', 'additionalProperties', 'outputContractVersion', 'jevPolicyVersion', 'protocolFallback', 'sourceJevCallId', 'minimumOrdinalScore', 'verificationBoundary', 'expectedArtifact', 'evidenceBoundary', 'https://json-schema.org/draft/2020-12/schema', 'verificationEngine', 'jev-llm-fallback']);
export const PRODUCTION_VERIFIER_DIAGNOSTIC_LITERALS = ['verifier-decision-diagnostic-v1', 'verifierDiagnosticsVersion', 'verifierDiagnostic', 'verifier-study-strategy-v2', 'verifier-study-source-v3', 'verifier-study-source-v4', 'verifier-study-source-v5', 'verifier-study-source-v6', 'invalid-response-type', 'response-too-large', 'duplicate-json-key', 'schema-structure', 'candidate-id-coverage', 'abstain-selects-candidate', 'accept-without-selected-id', 'selected-id-not-scored', 'selected-score-below-minimum', 'selected-score-not-highest', 'utf16-code-unit', 'expectedCandidateCount', 'uniqueCandidateCount', 'missingCandidateCount', 'unknownCandidateCount', 'duplicateCandidateCount', 'VerifierDecisionError', 'unrecognized_keys', '$.decision', '$.selectedCandidateId', '$.scores', '$.scores[]', '$.scores[].candidateId', '$.scores[].score', '$.scores[].reason', '$.reason'] as const;
export const PRODUCTION_ACCEPTANCE_POLICY_LITERALS = ['production-acceptance-diagnostics-v1', 'production-acceptance-planning-v1', 'acceptanceDiagnosticsVersion', 'acceptancePlanningVersion', 'acceptanceDiagnostic', 'acceptanceCapacity', 'oversizedStepCheckIndices', 'checkCountExceedsLimit', 'maxSteps', 'maxChecks', 'checkCount', 'stepCounts', 'sourceSha256'] as const;
export const PRODUCTION_ACCEPTANCE_GROUP_POLICY_LITERALS = ['acceptanceStrategy', 'planned-groups-v1', 'production-acceptance-plan-v1', 'production-acceptance-group-v1', 'production-acceptance-construction-v1', 'production-html-grouped-v1', 'acceptanceConstruction', 'acceptanceConstructionHash', 'acceptanceConstructionBoundary', 'acceptanceConstructionVersion', 'acceptancePlanVersion', 'acceptanceGroupVersion', 'AcceptancePlanError', 'acceptance-plan', 'sourceCandidateId', 'sourceCallId', 'rawOutputSha256', 'valueSha256', 'generationCallIds', 'compositeCandidateId', 'checksSha256', 'acceptancePlanHash', 'constructionAttemptId',
  'plan-structure', 'plan-source-quote', 'plan-binding', 'group-structure', 'group-order', 'non-json-input',
  'Acceptance construction rejected: plan-structure', 'Acceptance construction rejected: plan-source-quote', 'Acceptance construction rejected: plan-binding', 'Acceptance construction rejected: group-structure', 'Acceptance construction rejected: group-order', 'Acceptance construction rejected: non-json-input',
  'Duplicate obligation ID', 'Duplicate group ID', 'Acceptance slot count must be between 2 and 12', 'Duplicate check ID', 'Duplicate obligation reference', 'Unknown obligation reference', 'Unreferenced obligation', 'Both original sources must be referenced',
  'Acceptance check must preserve original values', 'Acceptance checks must match planned slots', 'Acceptance check exceeds its planned step budget', 'Acceptance input must be bounded JSON data',
] as const;
const protectedDiagnosticLiterals = ['production-json-diagnostics-v1', 'production-json-diagnostics-v2', 'outputDiagnosticsVersion', 'outputDiagnostic', ...PRODUCTION_ACCEPTANCE_POLICY_LITERALS, ...PRODUCTION_ACCEPTANCE_GROUP_POLICY_LITERALS, ...PRODUCTION_VERIFIER_DIAGNOSTIC_LITERALS, ...IMPLEMENTATION_EVIDENCE_PROTOCOL_LITERALS] as const;
export const productionApiKeySchema = z.string().min(16, credentialMessage).max(500, credentialMessage).refine(value => /^[\x21-\x7e]+$/.test(value) && !/["'\\]/.test(value), credentialMessage).refine(value => !reservedCredentialValues.has(value) && [...protectedJsonOutputLiterals, ...protectedDiagnosticLiterals].every(literal => !literal.includes(value)) && !/^(?:production-(?:html|acceptance|acceptance-semantic|coverage-owners|delivery|submission|global-repair|output-contract)-v\d+|production-camera-(?:scene|acceptance|delivery)-v\d+|raw-wire-usage-v\d+|verifier-(?:(?:phase-)?ordinal|compact-output)-v\d+|camera-(?:scene-runtime|hand-worker|scene-behavior|test-semantics)-v\d+|hand-geometry-v\d+|mediapipe-hand-v\d+|jev-candidate-v\d+|visible-token-v\d+|mock-package-v\d+|city-agent-autonomous-production-public-v\d+)$/.test(value), 'API Key 不得与平台协议字段、状态或版本标识相同，或包含于受保护的 JSON 运输协议标识中');
reservedCredentialValues.add('harnessPromptTransportVersion');
reservedCredentialValues.add('harness-literal-prompt-v1');
reservedCredentialValues.add('reviewContextVersion');
reservedCredentialValues.add('production-review-context-v1');
reservedCredentialValues.add('production-review-context-v2');
reservedCredentialValues.add('generationCodeReference');
reservedCredentialValues.add('role-call.userPrompt.context.feedback.previousHtml');
reservedCredentialValues.add('htmlExecutionProfileVersion');
reservedCredentialValues.add('production-html-execution-v1');
reservedCredentialValues.add('generationFeedbackReference');
reservedCredentialValues.add('sourceRoleCallIds');
reservedCredentialValues.add('role-call.userPrompt.context.regeneration');
for (const value of ['planningLoopVersion', PRODUCTION_PLANNING_LOOP_VERSION, 'planningFeedback', 'planningReviewContext', 'sourceRoleCallId', 'sourceCandidateId']) reservedCredentialValues.add(value);
for (const value of ['harnessJsonOutputVersion', 'harness-json-output-v1', 'responseFormatPolicy', 'deepseek-json-object-other-prompt-only']) reservedCredentialValues.add(value);
for (const value of ['executionIdentity', 'production-boot-disk-v1', 'execution-identity-unready', 'execution-identity-drift']) reservedCredentialValues.add(value);
for (const value of ['sourceFingerprint', 'buildFingerprint', 'nativeFormSubmission', 'independentPagePerCheck', 'cspDirectives']) reservedCredentialValues.add(value);
export const pricingSchema = z.object({ inputPerMillion: z.number().finite().nonnegative().max(10000), outputPerMillion: z.number().finite().nonnegative().max(10000), currency: z.enum(['USD', 'CNY']) }).strict();
const baseUrl = z.string().trim().url().max(500).refine(value => { const u = new URL(value); return ['http:', 'https:'].includes(u.protocol) && !u.username && !u.password && !u.search && !u.hash; }, 'Base URL 必须是无凭据/查询参数的 HTTP(S) 地址');
export const productionAgentInputSchema = z.object({ name: z.string().trim().min(1).max(80), role: z.enum(PRODUCTION_ROLES), provider: z.enum(['openai-compatible', 'anthropic', 'deepseek']).default('deepseek'), baseUrl: baseUrl.default('https://api.deepseek.com'), modelId: z.string().trim().min(1).max(150).default(PRODUCTION_DEFAULT_MODEL_ID), apiKey: productionApiKeySchema.nullable().optional(), enabled: z.boolean().default(true), pricing: pricingSchema.nullable().optional() }).strict();
export const productionAgentPatchSchema = productionAgentInputSchema.partial();
export type ProductionAgentInput = z.input<typeof productionAgentInputSchema>;
export interface ProductionAgent { id: string; name: string; role: ProductionRole; provider: 'openai-compatible' | 'anthropic' | 'deepseek'; baseUrl: string; modelId: string; hasApiKey: boolean; enabled: boolean; pricing?: z.infer<typeof pricingSchema>; }
export const productionLimitsSchema = z.object({ maxCalls: z.number().int().min(12).max(80).default(24), maxRepairCycles: z.number().int().min(0).max(2).default(2), maxTokens: z.number().int().min(2048).max(5_000_000).default(500000), maxOutputTokens: z.number().int().min(128).max(12000).default(6000), maxDurationMs: z.number().int().min(1000).max(1800000).default(600000), maxCost: z.number().finite().positive().max(10000).default(5), currency: z.enum(['USD', 'CNY']).default('USD') }).strict();
export const cameraConstraintSchema = z.object({ openPalm: z.enum(['scatter', 'gather']).optional(), closedFist: z.enum(['scatter', 'gather']).optional(), palmX: z.enum(['rotate', 'none']).optional() }).strict().refine(value => Object.keys(value).length > 0, '至少声明一个手势动作要求；全部未指定时省略该字段').refine(value => !value.openPalm || !value.closedFist || value.openPalm !== value.closedFist, '张掌与握拳动作要求必须相反，不能同时散开或聚合');
export const productionRunInputSchema = z.object({ brief: z.string().trim().min(3).max(6000), capability: z.enum(PRODUCTION_CAPABILITIES).default('offline-single-html'), cameraBusinessConstraints: cameraConstraintSchema.optional(), mode: z.enum(['demo', 'mock-jev', 'live']).default('demo'), verifierEngine: z.enum(['llm-rubric', 'jev-cascade']).default('llm-rubric'), implementationEvidencePolicy: z.enum(['legacy', 'source-bound-v1']).default('legacy'), acceptanceStrategy: z.literal('planned-groups-v1').optional(), demoCaseId: z.enum(['create', 'feature', 'bugfix']).optional(), agentIds: z.array(z.string().uuid()).length(6), candidateCount: z.union([z.literal(1), z.literal(2)]).default(1), limits: productionLimitsSchema.default(() => productionLimitsSchema.parse({})), requirement: z.object({ id: z.string().trim().min(1).max(80), source: z.string().trim().min(1).max(300), background: z.string().max(3000).default(''), acceptance: z.string().trim().min(1).max(3000), difficulty: z.enum(['low', 'medium', 'high']).default('low'), kind: z.enum(['illustrative', 'user-declared-real']).default('illustrative') }).strict(), budgetAuthorized: z.boolean().default(false) }).strict().refine(input => !input.cameraBusinessConstraints || input.capability === 'camera-scene-v1', '结构化手势要求仅支持摄像头场景能力').refine(input => input.mode !== 'live' || input.demoCaseId === undefined, '真实运行不接受演示题专用配置').refine(input => input.capability !== 'camera-scene-v1' || input.mode === 'live', '摄像头场景能力只支持明确授权的真实模式，不接受演示夹具回退').refine(input => input.implementationEvidencePolicy === 'legacy' || input.capability === 'offline-single-html' && input.mode === 'live' && input.verifierEngine === 'llm-rubric', 'source-bound-v1 仅支持 live 离线HTML与 llm-rubric；不允许Mock、摄像头或Jev快速路径').refine(input => !input.acceptanceStrategy || input.mode === 'live' && input.capability === 'offline-single-html' && input.verifierEngine === 'llm-rubric' && input.candidateCount === 1 && input.implementationEvidencePolicy === 'legacy', 'planned-groups-v1 仅支持 live 离线HTML、LLM、单候选及legacy证据策略；不静默降级');
export type ProductionRunInput = z.infer<typeof productionRunInputSchema>;
export type ProductionRunStatus = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled' | 'interrupted';
export interface ProductionResponseFormat { version: string; mode: 'json-object' | 'prompt-only'; evidence: 'not-networked' | 'requested' | 'wire-observed'; }
export interface ProductionProviderUsage { requests: number; deniedRequests: number; status: number | null; transportComplete: boolean; httpEof?: boolean; protocolComplete?: boolean; inputReported: boolean; outputReported: boolean; inputTokens: number | null; outputTokens: number | null; complete: boolean; responseFormat?: ProductionResponseFormat; }
export interface ProductionCall { id: string; role: ProductionRole; candidateId: string; phase: string; executionSource: 'mock' | 'injected' | 'harness'; verificationEngine?: 'llm-rubric' | 'jev-llm-fallback' | 'jev-llm-protocol-fallback'; sourceJevCallId?: string; providerRequests?: ProductionProviderUsage; responseFormat?: ProductionResponseFormat; startedAt: string; finishedAt?: string; model: Pick<ProductionAgent, 'id' | 'provider' | 'baseUrl' | 'modelId'>; promptVersion: string; promptHash: string; configHash: string; systemPrompt: string; userPrompt: string; rawOutput: string; error?: string; outputDiagnostic?: JsonOutputDiagnostic; acceptanceDiagnostic?: AcceptanceCapacityDiagnostic; verifierDiagnostic?: VerifierDecisionDiagnostic; implementationEvidenceDiagnostic?: ImplementationEvidenceDiagnostic; usage: { inputTokens: number | null; outputTokens: number | null; estimatedCost: number | null; currency: string }; selected?: boolean; }
export interface ProductionEvent { id: string; time: string; phase: string; role?: ProductionRole; message: string; }
export interface ProductionVerification { phase: string; engine?: 'llm-rubric' | 'jev' | 'jev-llm-fallback' | 'jev-llm-protocol-fallback'; sourceJevCallId?: string; candidateIds: string[]; selectedCandidateId: string | null; criteriaHash: string; scores: Array<{ candidateId: string; score: number; reason: string }>; decision: 'accept' | 'abstain'; reason: string; verifierDiagnostic?: VerifierDecisionDiagnostic; implementationEvidenceDiagnostic?: ImplementationEvidenceDiagnostic; implementationEvidenceContract?: ImplementationEvidenceContract; implementationEvidence?: ImplementationEvidence; }
export interface ProductionJevCall { id: string; phase: string; startedAt: string; configHash: string; evaluation: JevEvaluation; }
export interface ProductionGate { passed: boolean; failureKind?: 'infrastructure' | 'timeout'; checks: Array<{ name: string; passed: boolean; detail?: string }>; summary?: string; evidenceScope?: 'scene-behavior-synthetic'; }
export interface ProductionRepair { id: string; time: string; phase: string; role: Exclude<ProductionRole, 'verifier'>; kind: 'stage-regeneration' | 'gate-repair'; attempt: number; reason: string; rejectedCandidateIds: string[]; frozenHash: string | null; }
export interface ProductionAcceptanceGroupSource { groupId: string; sourceCallId: string; sourceCandidateId: string; rawOutputSha256: string; valueSha256: string; value: AcceptanceGroup; }
export interface ProductionAcceptanceConstruction {
  version: 'production-acceptance-construction-v1';
  plan: { sourceCallId: string; sourceCandidateId: string; rawOutputSha256: string; valueSha256: string; value: AcceptancePlan };
  attempts: Array<{ id: string; startedAt: string; finishedAt?: string; decision: 'building' | 'rejected' | 'accepted'; generationCallIds: string[]; groups: ProductionAcceptanceGroupSource[]; compositeCandidateId?: string; checks?: AcceptanceCheck[]; checksSha256?: string; reviewCallId?: string; error?: string }>;
}
// Optional opt-in evidence; old persisted runs and public archives are not migrated.
export interface ProductionRun { acceptanceConstruction?: ProductionAcceptanceConstruction; }
export interface ProductionRun { id: string; input: ProductionRunInput; status: ProductionRunStatus; createdAt: string; finishedAt?: string; durationMs?: number; evidenceKind: 'fixture' | 'fixture-with-real-jev' | 'real-model' | 'injected-test'; platformCommit?: string; executionIdentity?: ProductionExecutionIdentity; validationContract?: ProductionValidationContract; cameraVerification?: CameraVerification; jevSnapshot?: JevPublicConfig; jevCalls?: ProductionJevCall[]; agentSnapshot: ProductionAgent[]; events: ProductionEvent[]; calls: ProductionCall[]; verifications: ProductionVerification[]; outputs: Array<{ phase: string; role: ProductionRole; value: unknown; selectedCandidateId: string }>; frozenContract?: { version: string; hash: string; requirementHash: string; checks: unknown[]; frozenAt: string; validationContractHash?: string; capability?: ProductionCapability; runtimeVersion?: string; runtimeHash?: string; mandatoryChecksVersion?: string }; gateHistory: ProductionGate[]; gate?: ProductionGate; repairs: number; repairPolicyVersion?: typeof PRODUCTION_REPAIR_POLICY_VERSION; repairHistory?: ProductionRepair[]; error?: string; usage: { inputTokens: number | null; outputTokens: number | null; estimatedCost: number | null; currency: string; complete: boolean }; interventions: Array<{ time: string; reason: string; type: 'cancel' }>; artifacts: Array<{ name: string; type: string }>; }
