import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';

const output = path.resolve('output/submission-video'); mkdirSync(output, { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1600, height: 900 }, acceptDownloads: true, recordVideo: { dir: output, size: { width: 1600, height: 900 } } });
const page = await context.newPage(); page.on('dialog', dialog => void dialog.accept());
await page.goto('http://127.0.0.1:4173/city-agent/');
await page.getByRole('button', { name: 'AI 生活服务会员', exact: true }).waitFor();
const started = Date.now();
const holdUntil = async (seconds: number) => { const delay = Math.max(0, seconds * 1000 - (Date.now() - started)); await page.waitForTimeout(delay); };
const captions: { at: number; text: string }[] = [];
const caption = async (text: string) => {
  captions.push({ at: (Date.now() - started) / 1000, text });
  await page.evaluate(text => {
    let element = document.getElementById('recording-caption');
    if (!element) { element = document.createElement('div'); element.id = 'recording-caption'; element.setAttribute('style', 'position:fixed;z-index:2147483646;bottom:16px;left:290px;right:30px;background:rgba(12,35,48,.96);color:white;border-left:5px solid #70c6ae;padding:16px 24px;border-radius:8px;font:21px/1.6 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;pointer-events:none;box-shadow:0 5px 25px #0003;'); document.body.append(element); }
    (document.querySelector('dialog[open]') ?? document.body).append(element);
    element.textContent = text;
  }, text);
  console.log(`Video chapter ${Math.round((Date.now() - started) / 1000)}s: ${text}`);
};
await caption('City Agent｜虚拟社会调查。本视频先跑工程演示，再载入已留档的真实模型问卷。载入快照不会新增API请求，合成实验也不是真人调研。');
await holdUntil(25);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人口来源与方法/ }).click();
await caption('人口底座：冻结2020七普常住口径，三个街道共503,859人。最新区级总量单独记录，不把它直接外推成街道结构。');
await holdUntil(42);
await page.locator('.pages-evidence h3').scrollIntoViewIfNeeded();
await caption('原件、页表行列与SHA-256可回查。街道×年龄×性别联合为独立性推断；具体年龄和业务资格标为假设，不自动赋予商品偏好。');
await holdUntil(60);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人群 Agent 预设/ }).click();
await caption('人群Agent与研发角色分开：一般成年居民、照护者、养猫与养犬购买者各有资格设定。预设数量不等于真实人群数量。');
await holdUntil(73);
const card = page.locator('.resident-grid .agent-card').filter({ has: page.getByRole('heading', { name: '一般成年居民', exact: true }) });
await card.getByRole('button', { name: '编辑配置' }).click();
await page.getByRole('dialog').getByLabel(/^Provider/).scrollIntoViewIfNeeded();
await caption('每个Agent可以独立设置Provider、Base URL、Model ID与API Key。Key在页面填写，仅在当前会话使用，刷新后清除；本视频不填写Key。');
await holdUntil(91);
await page.getByRole('button', { name: '关闭人群配置', exact: true }).click();
await card.getByRole('button', { name: '复制人群 一般成年居民', exact: true }).click();
await caption('复制预设可快速形成不同模型或情景版本；画像和资格仍需核验，复制不会创造真实人口或证明代表性。');
await holdUntil(105);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /虚拟社会调查/ }).click();
await page.getByRole('button', { name: 'AI 生活服务会员', exact: true }).click();
await page.locator('.resident-choice').filter({ hasText: '一般成年居民' }).first().getByRole('checkbox').check();
await caption('加载通用AI会员案例：15题覆盖使用情景、功能、隐私、套餐与价格。支持单选、多选、量表、数值和开放题；可编辑或导入JSON。');
await holdUntil(122);
await page.getByRole('button', { name: '检查问卷与人群', exact: true }).click();
await page.locator('.research-check').scrollIntoViewIfNeeded();
await caption('预检不调用模型。15–59岁人口档不能准确识别18+分母，所以成年研究保留资格缺口。模拟实验可以继续，但不计算总体权重。');
await holdUntil(145);
const panel = page.getByRole('region', { name: '问卷仿真与结果' });
await panel.scrollIntoViewIfNeeded();
await panel.getByRole('checkbox').check();
await caption('计划12个覆盖画像，seed=42。确认显式假设后运行工程演示；真实模型模式则逐人发送独立画像与同一份冻结问卷。');
await holdUntil(158);
await panel.getByRole('button', { name: '运行问卷演示' }).click();
await panel.getByRole('heading', { name: '工程演示结果 · 规则答卷 · 12/12 有效' }).waitFor();
await panel.locator('.survey-run-results').scrollIntoViewIfNeeded();
await caption('12份有效规则答卷，0次模型调用、0 Token、0 API费用。严格检查题目ID、选项、必答与数值边界；失败和未开始画像不会被填补成成功。');
await holdUntil(175);
await panel.getByRole('button', { name: '查看已发布实测 · 无需Key' }).click();
await panel.getByRole('heading', { name: '模型仿真结果 · 12/12 有效' }).waitFor();
await panel.locator('.survey-run-results').scrollIntoViewIfNeeded();
await caption('现在载入真实Flash基准：12个独立画像、15题、12次Harness调用，12/12有效。查看冻结耗时、Token与计价依据；这是已完成运行，不是本视频重新请求模型。');
await holdUntil(190);
const choices = panel.locator('.survey-run-results > details').filter({ has: page.locator('summary').filter({ hasText: '价格／权益配对比较' }) });
await choices.locator('summary').first().click(); await choices.scrollIntoViewIfNeeded();
await caption('统计由程序确定性计算，保留有效分母。页面有街道/年龄/预设分组与问卷内价格追问；独立价格实验和负结果另存附件，不把问卷追问称为随机实验。');
await holdUntil(198);
const trace = panel.locator('.survey-run-results > details').filter({ has: page.locator('summary').filter({ hasText: '回查画像、硬约束诊断与原始答卷' }) }); await trace.locator('summary').first().click(); await trace.locator('details').first().locator('summary').click(); await trace.scrollIntoViewIfNeeded();
await caption('逐数字回查：resident ID连接画像假设、原始JSON、硬约束诊断与题目ID。五次重复与消融中存在无效选项和不稳定结论，全部保留而非补填成功。');
await holdUntil(206);
const downloaded = page.waitForEvent('download'); await panel.getByRole('button', { name: '导出运行证据包' }).click(); await (await downloaded).saveAs(path.join(output, 'recorded-live-snapshot.json'));
await caption('导出的证据包冻结问卷、人口版本、画像、Prompt、原始答卷、统计和运行账本，不含API Key。真实费用缺usage或单价时显示未知。');
await holdUntil(220);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /申报材料与演示/ }).click();
await caption('申报附件含完整问卷、49次当前实验、早期失败与勘误。公网不运行四角色Harness；本机交付另有冻结Gate证据。下一步提高答卷稳定性，再做真人或业务留出校准。');
await holdUntil(240);
writeFileSync(path.join(output, 'captions.json'), JSON.stringify(captions, null, 2));
const video = page.video()!; await context.close(); await video.saveAs(path.join(output, 'city-agent-demo.webm')); await browser.close();
console.log(`Recorded actual browser session: ${((Date.now() - started) / 1000).toFixed(1)} seconds.`);
