import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { chromium } from 'playwright';

// Actual browser recording requested by the user, not an animated mock UI or live-model reenactment.
const directory = path.resolve('output/review-video'); await mkdir(directory, { recursive: true });
const output = path.join(directory, `review-demo-${Date.now()}`); await mkdir(output);
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1600, height: 1000 }, recordVideo: { dir: output, size: { width: 1600, height: 1000 } } });
const recordingRequestedAt = Date.now();
const page = await context.newPage(); page.on('dialog', dialog => void dialog.accept());
const requests: string[] = []; const errors: string[] = [];
page.on('pageerror', error => errors.push(error.message));
await page.route('**/*', async route => {
  const request = route.request(); const url = new URL(request.url());
  if (url.hostname !== '127.0.0.1' || !['GET', 'HEAD'].includes(request.method())) {
    requests.push(`${request.method()} ${url.origin}${url.pathname}`); await route.abort('blockedbyclient'); return;
  }
  await route.continue();
});
await page.goto('http://127.0.0.1:4173/city-agent/#research');
await page.getByRole('button', { name: '完整业务示例 · 零费用体验', exact: true }).waitFor();
const started = Date.now(); const captions: { at: number; text: string }[] = [];
const hold = async (seconds: number) => page.waitForTimeout(Math.max(0, seconds * 1000 - (Date.now() - started)));
const caption = async (text: string) => {
  captions.push({ at: (Date.now() - started) / 1000, text });
  await page.evaluate(text => {
    let element = document.getElementById('review-caption');
    if (!element) { element = document.createElement('div'); element.id = 'review-caption'; element.style.cssText = 'position:fixed;z-index:2147483646;bottom:18px;left:280px;right:24px;padding:15px 20px;background:rgba(13,45,48,.97);border-left:4px solid #80d0b4;color:#fff;border-radius:8px;font:20px/1.65 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;pointer-events:none;'; }
    (document.querySelector('dialog[open]') ?? document.body).append(element); element.textContent = text;
  }, text);
  console.log(`Chapter ${Math.round((Date.now() - started) / 1000)}s: ${text}`);
};
await caption('City Agent｜本候选实际浏览器录屏。将运行小学照护者与宠物零食两套完整工程问卷；全程不填Key、不请求模型。它不是滨江真人偏好或开店结论。');
await hold(23);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人口来源与方法/ }).click();
await caption('人口底座：2020七普503,859人、三个街道；最新全区总量另册记录。年龄×性别联合为显式独立性推断，不能外推成2026实时街道人口或养宠/家长分母。');
await hold(47);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人群 Agent 预设/ }).click();
const resident = page.locator('.resident-grid .agent-card').filter({ has: page.getByRole('heading', { name: '一般成年居民', exact: true }) });
await resident.getByRole('button', { name: '编辑配置', exact: true }).click();
await page.getByRole('region', { name: '五层人群情景构建' }).scrollIntoViewIfNeeded();
await caption('五层构建：人格倾向、成长、教育、当前家庭、工作与收入口径。未知用null，不用DNA标签，也不由收入、学历推算商品偏好；支持勾选与自定义。');
await hold(70);
await page.getByRole('dialog').getByLabel(/^Provider/).scrollIntoViewIfNeeded();
await caption('每个Agent可独立配置Provider、Base URL、Model ID和页面Key，并可复制。公网Key仅会话内存；本机真实执行通过锁定DeepSeek Harness SDK。此处不填写Key。');
await hold(89);
await page.getByRole('button', { name: '关闭人群配置', exact: true }).click();
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /虚拟社会调查/ }).click();
await page.getByRole('button', { name: '完整业务示例 · 零费用体验', exact: true }).click();
const panel = page.getByRole('region', { name: '完整业务工程自证' });
await panel.scrollIntoViewIfNeeded();
await panel.getByRole('button', { name: '运行完整业务自证 · 0 API费用', exact: true }).click();
await panel.getByRole('heading', { name: '工程演示结果 · 规则答卷 · 12/12 有效', exact: true }).waitFor();
await panel.locator('.survey-run-results h3').scrollIntoViewIfNeeded();
await caption('小学场景：17题、四份五层情景、12个不同实例，0模型/Token/API费。购买与许可由假设成年照护者回答；孩子本人口味12份均未采集，不能拿家长回答替代。');
await hold(116);
const childTaste = panel.locator('.survey-run-results > details').filter({ has: page.locator('summary').filter({ hasText: '孩子本人表达的具体口味' }) });
await childTaste.locator('summary').click(); await childTaste.scrollIntoViewIfNeeded();
await caption('未知和不购买进入分母：预算null不填0；明确不购买预算为0。所有统计可回查每人raw。跨题逻辑只审计已登记规则，不宣称全面语义正确或市场有效。');
await hold(135);
let download = page.waitForEvent('download'); await panel.getByRole('button', { name: '导出运行与跨题自证', exact: true }).click();
await (await download).saveAs(path.join(output, 'recorded-child-proof.json'));
await panel.getByLabel('完整业务问卷').selectOption('pet-snacks');
await panel.getByRole('button', { name: '运行完整业务自证 · 0 API费用', exact: true }).click();
await panel.getByRole('heading', { name: '工程演示结果 · 规则答卷 · 12/12 有效', exact: true }).waitFor();
await panel.locator('.survey-run-results h3').scrollIntoViewIfNeeded();
await caption('宠物场景：18题，猫/犬资格、过去零食购买、统一50克价位与线上履约分开。猫狗数量是人为情景覆盖，不是滨江占比；零食不能推出主粮主营比例。');
await hold(160);
const trace = panel.locator('.survey-run-results > details').filter({ has: page.locator('summary').filter({ hasText: '回查画像、硬约束诊断与原始答卷' }) });
await trace.locator('summary').first().click(); await trace.locator('details').first().locator('summary').click(); await trace.scrollIntoViewIfNeeded();
await caption('每人证据链：人口版本→资格与五层assumption→冻结Prompt→原始JSON→结构/跨题校验→分组统计。哈希证明一致性，不认证真人身份或实际供应商调用。');
await hold(184);
download = page.waitForEvent('download'); await panel.getByRole('button', { name: '导出运行与跨题自证', exact: true }).click();
await (await download).saveAs(path.join(output, 'recorded-pet-proof.json'));
const historyId = await panel.getByLabel('业务自证历史').inputValue();
await page.reload(); await page.getByRole('button', { name: '完整业务示例 · 零费用体验', exact: true }).click();
await panel.getByLabel('业务自证历史').selectOption(historyId);
await panel.getByRole('button', { name: '导出运行与跨题自证', exact: true }).waitFor();
await panel.locator('.survey-run-results h3').scrollIntoViewIfNeeded();
await caption('刷新后仍可恢复完整自证及当时的逻辑规则，不借用最新规则给旧结果补分。历史真实12×15与49次实验另册保留，不能把本次24个mock实例加入真实样本量。');
await hold(205);
await page.getByRole('button', { name: '从自然语言规划调查', exact: true }).click();
await page.getByRole('region', { name: '自然语言研究规划' }).scrollIntoViewIfNeeded();
await caption('自然语言规划可生成候选后显式应用，不自动启动居民。此视频没有Key，所以不请求规划模型；真实规划质量和30人完整率仍待另行预算实测。');
await hold(224);
await page.getByRole('button', { name: '检查业务证据包', exact: true }).click();
const evidence = page.getByRole('region', { name: '业务证据包预检' });
await evidence.getByRole('button', { name: '检查业务证据包 · 不调用模型', exact: true }).click();
await evidence.getByRole('heading', { name: '业务证据仍有缺口', exact: true }).waitFor(); await evidence.scrollIntoViewIfNeeded();
await caption('没有候选点/客流/租金、真实资格分母、订单与试售时明确needs-data。现实桥MCP、wiki/dream、有限自主性尚为规划；当前价值是研究前测和可追溯补采，不承诺真实开店盈利。');
await hold(247);
await caption('本候选：两套完整问卷、五层方法、原文和成本账本随申报附件。旧公开入口保留；新候选尚待发布确认，正式提交以回执为准。');
await hold(260);
if (requests.length || errors.length) throw new Error(`录屏未通过零调用/页面异常核验：${JSON.stringify({ requests, errors })}`);
const video = page.video()!; await context.close(); const webm = path.join(output, 'actual-browser.webm'); await video.saveAs(webm); await browser.close();
const duration = (Date.now() - started) / 1000;
const recordingOffset = (started - recordingRequestedAt) / 1000;
await writeFile(path.join(output, 'captions.json'), JSON.stringify({ actualBrowserRecording: true, realModelCalls: 0, requestedExternalOrWrites: requests, pageErrors: errors, durationSeconds: duration, captionOffsetSeconds: recordingOffset, captions }, null, 2), { flag: 'wx' });
const stamp = (value: number) => { const milliseconds = Math.round(value * 1000); return `${String(Math.floor(milliseconds / 3600000)).padStart(2, '0')}:${String(Math.floor(milliseconds / 60000) % 60).padStart(2, '0')}:${String(Math.floor(milliseconds / 1000) % 60).padStart(2, '0')}.${String(milliseconds % 1000).padStart(3, '0')}`; };
const vtt = 'WEBVTT\n\n' + captions.map((item, index) => `${stamp(item.at + recordingOffset)} --> ${stamp((captions[index + 1]?.at ?? duration) + recordingOffset)}\n${item.text}\n`).join('\n');
await writeFile(path.join(output, 'demo-next.vtt'), vtt, { flag: 'wx' });
const mp4 = path.join(directory, `demo-next-${path.basename(output)}.mp4`);
execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-i', webm, '-c:v', 'libx264', '-preset', 'fast', '-crf', '23', '-pix_fmt', 'yuv420p', '-movflags', '+faststart', '-an', mp4]);
console.log(JSON.stringify({ mp4, output, durationSeconds: duration, realModelCalls: 0, audio: 'none-captioned' }, null, 2));
