import assert from 'node:assert/strict';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { chromium } from 'playwright';
import { fixtureAnswers, type Profile } from '../shared/survey-engine';
import { getResearchTemplates } from '../server/research/templates';

const output = path.resolve('output/pages-qa'); mkdirSync(output, { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1600, height: 900 }, acceptDownloads: true });
const page = await context.newPage(); const errors: string[] = [];
page.on('pageerror', error => errors.push(error.message));
page.on('dialog', dialog => void dialog.accept());
await page.goto(process.env.CITY_PAGES_URL ?? 'http://127.0.0.1:4173/city-agent/');
await page.getByRole('button', { name: 'AI 生活服务会员', exact: true }).click();
await page.locator('.resident-choice').filter({ hasText: '一般成年居民' }).getByRole('checkbox').check();
await page.getByRole('button', { name: '检查问卷与人群', exact: true }).click();
await page.locator('.research-check').getByText('一般成年居民 · 人群资格或证据待补充', { exact: true }).waitFor();
const panel = page.getByRole('region', { name: '问卷仿真与结果' });
await panel.getByRole('checkbox').check();
await panel.getByRole('button', { name: '运行问卷演示' }).click();
await panel.getByRole('heading', { name: '工程演示结果 · 规则答卷 · 12/12 有效' }).waitFor();
assert.ok(await panel.locator('.survey-run-results > details').count() >= 16);
await panel.scrollIntoViewIfNeeded(); await page.screenshot({ path: path.join(output, 'fixture.png') });
const downloadRun = async (name: string) => {
  const promise = page.waitForEvent('download'); await panel.getByRole('button', { name: '导出运行证据包' }).click();
  const download = await promise; const target = path.join(output, name); await download.saveAs(target); return JSON.parse(readFileSync(target, 'utf8'));
};
const fixture = await downloadRun('fixture.json'); assert.equal(fixture.metrics.valid, 12); assert.equal(fixture.metrics.modelCalls, 0);
await page.getByRole('button', { name: '保存调查草稿', exact: true }).click();
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人口来源与方法/ }).click();
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /虚拟社会调查/ }).click();
await panel.getByRole('heading', { name: '工程演示结果 · 规则答卷 · 12/12 有效' }).waitFor();
assert.equal((await downloadRun('after-navigation.json')).id, fixture.id);
await page.reload(); await panel.getByRole('heading', { name: '工程演示结果 · 规则答卷 · 12/12 有效' }).waitFor();
assert.equal((await downloadRun('after-reload.json')).id, fixture.id);
await panel.getByRole('button', { name: '查看已发布实测 · 无需Key' }).click();
await panel.getByRole('heading', { name: '模型仿真结果 · 12/12 有效' }).waitFor();
const published = await downloadRun('published-live.json'); assert.equal(published.mode, 'live'); assert.equal(published.metrics.modelCalls, 12);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人群 Agent 预设/ }).click();
const card = page.locator('.resident-grid .agent-card').filter({ has: page.getByRole('heading', { name: '一般成年居民', exact: true }) });
await card.getByRole('button', { name: '编辑配置' }).click();
const dialog = page.getByRole('dialog');
const canary = 'qa-only-not-a-real-credential';
await dialog.getByLabel(/^Provider/).selectOption('openai-compatible');
await dialog.getByRole('textbox', { name: '画像说明', exact: true }).fill('QA画像：软件工程师，与两个孩子同住。');
await dialog.getByLabel('Base URL', { exact: true }).fill('https://model.example.invalid/v1');
await dialog.getByLabel('Model ID', { exact: true }).fill('mock-contract-only');
await dialog.getByLabel('API Key', { exact: true }).fill(canary);
await dialog.getByRole('button', { name: '保存人群预设' }).click();
await card.getByText('本次会话已填写 · 连通性未验证', { exact: true }).waitFor();
await card.getByRole('button', { name: '复制人群 一般成年居民', exact: true }).click();
await page.locator('.resident-grid .agent-card').filter({ has: page.getByRole('heading', { name: '一般成年居民 副本', exact: true }) }).getByText('本次会话已填写 · 连通性未验证', { exact: true }).waitFor();
const storage = await page.evaluate(() => JSON.stringify({ local: { ...localStorage }, session: { ...sessionStorage } }));
assert.equal(storage.includes(canary), false);
let calls = 0;
await page.route('https://model.example.invalid/v1/chat/completions', async route => {
  calls++; const request = route.request(); assert.equal(request.headers().authorization, `Bearer ${canary}`);
  const body = request.postDataJSON(); assert.equal(body.model, 'mock-contract-only'); assert.equal(body.stream, false);
  const input = JSON.parse(body.messages[1].content) as { resident: Profile };
  assert.ok(input.resident.description.includes('软件工程师'));
  await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ choices: [{ message: { content: fixtureAnswers(getResearchTemplates()[2], input.resident, 42) } }], usage: { prompt_tokens: 10, completion_tokens: 5 } }) });
});
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /虚拟社会调查/ }).click();
await panel.getByRole('checkbox').check();
await panel.getByLabel(/^运行方式/).selectOption('live');
await panel.getByLabel('计划受访者', { exact: true }).fill('1');
await panel.getByRole('button', { name: '开始真实模型调查' }).click();
await panel.getByRole('heading', { name: '模型仿真结果 · 1/1 有效' }).waitFor();
const mocked = await downloadRun('mocked-protocol.json');
assert.equal(calls, 1); assert.equal(mocked.metrics.inputTokens, 10); assert.equal(mocked.metrics.outputTokens, 5); assert.equal(mocked.metrics.apiCostCny, null);
assert.equal(JSON.stringify(mocked).includes(canary), false);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人群 Agent 预设/ }).click();
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /虚拟社会调查/ }).click();
assert.equal((await downloadRun('after-resident-navigation.json')).id, mocked.id);
await panel.getByLabel(/^运行方式/).selectOption('live'); await panel.getByRole('checkbox').check();
await page.unroute('https://model.example.invalid/v1/chat/completions');
await page.route('https://model.example.invalid/v1/chat/completions', route => route.fulfill({ status: 401, contentType: 'application/json', body: '{"error":"mock rejection"}' }));
await panel.getByLabel('计划受访者', { exact: true }).fill('3');
await panel.getByRole('button', { name: '开始真实模型调查' }).click();
await panel.getByRole('heading', { name: '模型仿真结果 · 0/3 有效' }).waitFor();
const rejected = await downloadRun('mocked-rejected.json');
assert.equal(rejected.metrics.modelCalls, 1); assert.equal(rejected.metrics.failed, 1); assert.equal(rejected.metrics.notStarted, 2);
assert.equal(rejected.metrics.inputTokens, null); assert.equal(rejected.metrics.apiCostCny, null);
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /人群 Agent 预设/ }).click();
await page.reload(); await card.getByRole('button', { name: '编辑配置' }).waitFor();
assert.equal(await card.getByText('未配置', { exact: true }).count(), 1);
const copy = page.locator('.resident-grid .agent-card').filter({ has: page.getByRole('heading', { name: '一般成年居民 副本', exact: true }) });
assert.equal(await copy.getByText('未配置', { exact: true }).count(), 1);
await page.screenshot({ path: path.join(output, 'resident-config.png') });
await page.setViewportSize({ width: 390, height: 844 });
await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: /虚拟社会调查/ }).click();
await page.getByRole('button', { name: 'AI 生活服务会员', exact: true }).click();
await page.screenshot({ path: path.join(output, 'mobile.png'), fullPage: true });
const overflow = await page.evaluate(() => document.documentElement.scrollWidth - innerWidth);
assert.ok(overflow <= 1, `Mobile overflow ${overflow}px`); assert.deepEqual(errors, []);
writeFileSync(path.join(output, 'summary.json'), JSON.stringify({ fixture: { planned: 12, valid: 12, questions: 15 }, mockProtocolRequests: calls + 1, rejectedRequestStopsBatch: true, failureRetainsPlannedDenominator: true, unknownUsageAndCost: true, keyPersisted: false, keyExported: false, keysClearedOnReload: true, mobileOverflowPx: overflow, pageErrors: errors, actualModelCalls: 0 }, null, 2));
console.log('Pages QA passed: 15-question fixture, mocked protocol, clone, session-only Key, export, reload, mobile. No real model requests.');
await context.close(); await browser.close();
