import type { SurveyRun } from '../shared/survey-engine';
import { downloadJson } from './research-client';

export function SurveyResults({ run }: { run: SurveyRun }) {
  return <div className="survey-run-results"><h3>{run.mode === 'fixture' ? '工程演示结果 · 规则答卷' : '模型仿真结果'} · {run.metrics.valid}/{run.metrics.planned} 有效</h3>
    <p className="research-note"><strong>{run.task.title}</strong> · {run.startedAt} · {run.id} · {run.state === 'running' ? '部分进度快照；刷新后不自动续费重跑' : run.state}</p>
    <div className="pages-metrics"><span>耗时 <strong>{(run.durationMs / 1000).toFixed(2)} 秒</strong></span><span>模型调用 <strong>{run.metrics.modelCalls}</strong></span><span>Token <strong>{run.metrics.inputTokens === null || run.metrics.outputTokens === null ? '未知' : run.metrics.inputTokens + run.metrics.outputTokens}</strong></span><span>API费用 <strong>{run.metrics.apiCostCny === null ? '未知' : `¥${run.metrics.apiCostCny.toFixed(4)}`}</strong></span></div>
    <p className="research-note">结构有效 {run.metrics.structurallyValid ?? '未记录'} · 已登记硬矛盾 {run.metrics.contradictions ?? '未检查'} · 纳入统计 {run.metrics.valid} · 失败/无效 {run.metrics.failed} · 未开始 {run.metrics.notStarted}。有效不等于人格或市场效度通过。</p>
    {run.sampling && <details><summary>覆盖与重复画像 · {run.sampling.uniqueProfiles} 个不同画像</summary><p>覆盖单元 {run.sampling.coveredCells} · 重复画像 {run.sampling.duplicateProfiles} · 无总体权重</p>{run.sampling.streets.map(street => <p key={street.value}>{street.value}：{street.planned}人</p>)}{run.sampling.limitations.map(text => <p className="research-note" key={text}>{text}</p>)}</details>}
    {run.analysis && <>
      <details><summary>输出能力与问卷检查</summary>{run.analysis.outputs.map(output => <p key={output.output}>{output.output} · {output.status} · {output.detail}</p>)}<p>已登记画像硬规则 {run.analysis.questionnaireReview.profileRules} 条；未定义的语义检查不自动算通过。</p></details>
      <details><summary>人群比较 · 街道／年龄档／预设</summary>{run.analysis.groups.map(group => <details key={`${group.field}:${group.value}`}><summary>{group.field} · {group.value} · 有效 {group.valid}/{group.planned} · 不同画像 {group.uniqueProfiles}</summary>{group.summaries.map(summary => <div key={summary.questionId}><p>{summary.prompt} · 分母 {summary.denominator}</p>{summary.choices?.map(choice => <p key={choice.id}>{choice.label}：{choice.count}/{summary.denominator}</p>)}{summary.mean !== undefined && <p>均值 {summary.mean.toFixed(2)} · 中位数 {summary.median?.toFixed(2)} {summary.unit}</p>}</div>)}</details>)}</details>
      <details><summary>价格／权益配对比较 · 问卷内追问</summary>{run.analysis.comparisons.length ? run.analysis.comparisons.map(comparison => <div key={comparison.id}><h4>{comparison.label} · 配对分母 {comparison.denominator}</h4><p className="research-note">{comparison.interpretation}</p>{comparison.transitions.filter(pair => pair.count > 0).map(pair => <p key={`${pair.beforeId}:${pair.afterId}`}>{pair.beforeLabel} → {pair.afterLabel}：{pair.count}/{comparison.denominator}</p>)}</div>) : <p>未配置 comparisons；不能把逐题频数当价格实验。</p>}</details>
      <details><summary>条件研究简报与后续证据</summary><p>本批仅有 {run.analysis.hypothesisReport.valid}/{run.analysis.hypothesisReport.planned} 份纳入统计答卷，不给真实市场推荐。</p>{run.analysis.hypothesisReport.claims.map(claim => <p key={claim.id}>{claim.provenance} · {claim.claim}</p>)}{run.analysis.hypothesisReport.nextEvidence.map(text => <p key={text}>{text}</p>)}</details>
    </>}
    {run.summaries.map(summary => <details key={summary.questionId}><summary>{summary.prompt} · 有效分母 {summary.denominator}</summary>{summary.choices?.map(choice => <div className="survey-choice-result" key={choice.id}><span>{choice.label}</span><strong>{choice.count} / {summary.denominator}（{summary.denominator ? (choice.count / summary.denominator * 100).toFixed(1) : '—'}%）</strong></div>)}{summary.mean !== undefined && <p>均值 {summary.mean.toFixed(2)} {summary.unit} · 中位数 {summary.median?.toFixed(2)}</p>}{summary.type === 'text' && <p>开放回答原文见逐居民答卷及导出文件。</p>}</details>)}
    <details><summary>回查画像、硬约束诊断与原始答卷</summary>{run.profiles.map(profile => { const response = run.responses.find(value => value.residentId === profile.id); return <details key={profile.id}><summary>{profile.id} · {profile.streetName} · {profile.ageBand} · {response?.status ?? '尚未作答'}</summary><pre>{JSON.stringify({ profile, response }, null, 2)}</pre></details>; })}</details>
    <details><summary>人口结构审计、计价依据与运行参数</summary><pre>{JSON.stringify({ audit: run.populationAudit, pricing: run.pricing, parameters: run.parameters, timingBasis: run.timingBasis }, null, 2)}</pre><p>结构拟合不是外部验证；计价是估算，不是供应商账单。</p></details>
    <p className="hash-line">{run.hashAlgorithm} · 任务 {run.taskHash} · 人口 {run.populationHash}</p><button className="primary" onClick={() => downloadJson(run, `city-agent-survey-${run.id}.json`)}>导出运行证据包</button><p className="research-note">{run.metrics.pricingBasis}</p>
  </div>;
}
